version: "3.1"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD

  redis:
    image: redis
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
